### ISSUE TITLE
/reputation command includes if you reached your daily cap

### ISSUE THREAD

**Issue by GuuscoNL** [Bluesy1/CharB0T#100]
### Summary

/reputation command includes if you reached your daily cap.

### What is the feature request for?

Other exisiting features

### The Problem

The problem is that you might forget that you reached your daily cap later in the day if you reached it right after a new game is announced. (It happens to me at least)

### The Ideal Solution

The ideal solution is that a message like this appears when the /reputation command is send:
```
You have 729 reputation and you have reached your daily cap.
```
or
```
You have 729 reputation. 
You have reached your daily cap.
```
And if the daily cap has not been reached you can replace `have` with `haven't` (and maybe `yet` at the end of the sentence)
Maybe tell them how many points are left as well?

### The Current Solution

The current solution is to play a game and see at the end of the game if you have reached the daily cap. This takes time and might waste a lot of time if you play sudoku and get 0 points instead of 15 points, because you reached your daily cap.

### Additional Context

This is just a quality of life improvement, it makes life easier for the users.

**Comment by Bluesy1** [comment]
I'll add this to the list of things changed in my refractor in #84 which i hope to get done this weekend
