### ISSUE TITLE
Make all interaction based code translateable

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/CharB0T#198]
Currently, there are certain parts of charbot that aren't translateable, and there's no automated way to make them translateable.
I'd love to set up a method to allow them to be able to be translated, so the bot is more accessible.

**Comment by mrghannu** [comment]
Hello Sir, Can I contribute this issue?

**Comment by Bluesy1** [comment]
@mrghannu sure!
Let me know if you have any questions about how to go about it

**Comment by Bluesy1** [comment]
@mrghannu any status update on this?

**Comment by Bluesy1** [comment]
As there has been no progress orresponse in the past 9 days, I'm unassigning you from this.
