### ISSUE TITLE
Setup crowdin workflows

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/CharB0T#199]
Currently, i have to manually sync translations from crowdin, i'd love to be able to have that being done automatically

**Comment by CasparN** [comment]
https://github.com/jamiebuilds/crowdin-sync

I think this is something you need to do yourself and I can't do that.

**Comment by Bluesy1** [comment]
Maybe
I'd probably more do something like this:
https://github.com/Rapptz/discord.py/blob/master/.github/workflows/crowdin_download.yml
https://github.com/Rapptz/discord.py/blob/master/.github/workflows/crowdin_upload.yml

**Comment by Bluesy1** [comment]
After further thought, this is not needed right now,
