### ISSUE TITLE
Refractor: Use try-finally instead of try-except

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/CharB0T#233]
This is a simple issue, just requiring the 3 try except blocks to have the except block removed, and have the stuff after it moved into a finally statement

https://github.com/Bluesy1/CharB0T/blob/45b6356d4f73b285a700abc2b6a239b8ccb93745/charbot/events.py#L410-L462

**Comment by cereal-hecker** [comment]
hey, pls assign me this

**Comment by random9** [comment]
Hi
Can I enjoy as well?

**Comment by Bluesy1** [comment]
Hi @random9 !
there really isn't enough to do on this one for 2 people to do sadly.
If @cereal-hecker hasn't done it in a day or two, i'd be happy to let you do it instead though.
#228 should be pretty easy if you want to do that instead - its just converting some typehints

**Comment by random9** [comment]
ya thats cool i will be happy to do that I'm new around and i want to get more active. i will have a look
