### ISSUE TITLE
Refractor: `charbot/giveaway.py` extension into a package extension

### ISSUE THREAD

**Issue by Bluesy1** [Bluesy1/CharB0T#237]
Its hard to maintain/reference this extension as a single file, its matured to the point it deserves to be separated into a package based extension

- [ ] Turn `giveaway.py` into a package based extension
  - [ ] `__init__.py`
  - [ ] `cog.py`
  - [ ] `modal.py`
  - [ ] `view.py`
- [ ] Add unittests
- [ ] [Optional] add `__slots__` to frequently constructed classes in the extension.

**Comment by Sakshi-75** [comment]
Hi @Bluesy1 can I work on this?

**Comment by ShivamGarg2910** [comment]
@Bluesy1 , please assign it to me

**Comment by Bluesy1** [comment]
@ShivamGarg2910 i've assigned it to you
